# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: multiupload
version: '2.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/multiupload

page:
    title: 'Multiupload'
    perm: multiupload[]
    subpages:
        quickupload: { title: translate:quickupload }
        upload: { title: 'upload', hidden: true, hasLayout: false }

requires:
    redaxo: '>=5.0.0'