package: multiupload
version: '1.1.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/multiupload

page:
    title: 'Multiupload'
    perm: multiupload[]
    subpages:
        quickupload: { title: translate:quickupload}
        upload: { title: 'upload', hidden: true, hasLayout: false }

pages:
    mediapool/multiupload:
        title: 'Multiupload'
        perm: multiupload[]
        subpages:
          quickupload: { title: translate:quickupload, hidden: true}

requires:
    redaxo: ^5.0